.\" .UC 4
.TH "HEBREW-CAL" "1" "5 1 2014" "Avi Software" "hebrew-cal"
.SH "NAME"
hebrew-cal \- Hebrew Calendar
.PP 
.SH "DESCRIPTION"
 hebrew-cal is a beautifully designed Hebrew calendar
 which is very easy to use and customize.
 The calendar includes Hebrew dates, holidays,
 times, Parshiot Hashavua, Daf Yomi, and more.
 
 The appearance can be changed, the colors are editable
 and calendars can be printed.
.PP
.SH "SEE ALSO"
date(1), cal(1), hdate(1), hebcal(1), remind(1), hdate.h(3), hdate_struct(3)
.SH "AUTHOR"
Avi Software 2014.
